version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://user:password@db/resume_builder
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=resume_builder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d resume_builder"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
